### PR TITLE
Add to do list files for peer code review

### PR DESCRIPTION
**Pull request by Lembani**
This PR contains the To-Do List app.
> Highlights: A tool that helps to organize your day. It simply lists the things that you need to do and allows you to mark them as complete.

* **Setup environment**
1. Webpack
2. Jest
3. Project structure

* **Features**
- HTML markup structure
- CSS styles
- Add a task to localStrorage
- Remove a task from localStorage
- Edit a task
- Mark a task as complete
- Clear all completed tasks

* **Misc**
- Linters
- ReadMe
- License
- etc

### CODE REVIEW

**Comment by iKrystyan** [comment]
Good work on the effort put into the project. However, you still have to pass all linter tests. kindly correct that. Happy coding.

**Comment by Lembani** [comment]
> Good work on the effort put into the project. However, you still have to pass all linter tests. kindly correct that. Happy coding.

Thanks a lot for the review @Christianib003. 🙏🏾 
I have fixed the linter errors and I'd love it if you can review my project again, please. ✌🏾

**Comment by iKrystyan** [comment]
Good work on correcting the linters errors. Now you can merge the pull request. Happy coding.

**Comment by Lembani** [comment]
Thanks a lot @Christianib003, I really appreciate it. 🙏🏾

**Pull request merged**
